version: '3.9'
services:
  btcd:
    container_name: btcd
    build: ../docker-btcd
    volumes:
      - btcd-data:/btcd
      - rpc-data:/rpc
    networks:
      - app-network
  api:
    container_name: api
    build: .
    restart: on-failure
    depends_on:
      - btcd
    volumes:
      - ./:/usr/src/app
      - btcd-data:/btcd
      - rpc-data:/rpc
    ports:
      - '3000'
    networks:
      - app-network
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-network

volumes:
  btcd-data:
    external: false
    name: 'btcd-data'
  rpc-data:
    external: false
    name: 'rpc-data'

networks:
  app-network:
    driver: bridge
